### PR TITLE
feat: add grammar where `from` is optional

### PR DESCRIPTION
**Pull request by thalesmg**
Part of https://emqx.atlassian.net/browse/EMQX-11980

### CODE REVIEW

**Comment by thalesmg** [comment]
https://github.com/thalesmg/rulesql/actions/runs/8238743296

**Comment by zmstone** [comment]
maybe add ci in another pr, merge it to master first. then rebase this one.

**Comment by thalesmg** [comment]
> maybe add ci in another pr, merge it to master first. then rebase this one.

https://github.com/emqx/rulesql/pull/11

**Comment by thalesmg** [comment]
#12

**Pull request closed without merging**
